### ISSUE TITLE
Which Pod do the trigger files go in.

### ISSUE THREAD

**Issue by carukc** [TRIMM/traefik-maintenance#5]
Hello and forgive my ignorance... I am somewhat new to Traefik.

Do the '/path/to/maintenance.html' and '/path/to/maintenance.trigger' files go in the the Traefik pod?

Thanks
Chris

**Comment by ronaldtb** [comment]
Hi Chris,

My apologies for the extremely late reply and hopefully you already found the solution.
The files need to be readable by Traefik, so they should be located in the Traefik pod via a volume mapping.

Regards,

Ronald
